### ISSUE TITLE
one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by dahwang22** [ayu-22/BPPNet-Back-Projected-Pyramid-Network#6]
Hi, when I use dataset O-Haze and I-Haze to run "train(epochs)", the following error message appears:

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 512, 4, 4]], which is output 4 of BroadcastBackward, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
 
What is the cause？ Thx

**Comment by ayu-22** [comment]
Hi, To solve this issue, you can first do the gradient descent on the discriminator and then find the generator loss and do the gradient descent on it. 

Currently, we are calculating the loss of discriminator and generator simultaneously, and then in backward function, first gradient descent occurs on discriminator. Then we are doing gradient descent on generator loss, but as the discriminator is already updated, hence maybe because of this the error is coming as we are also using adversarial loss which depends on the discriminator, whose weights are updated.

You can first do the gradient descent on the discriminator and then calculate the generator loss and then do the gradient descent on generator loss. But, do consider that in our case this error didn't occur for the code which we have uploaded, so if you are doing some changes to resolve your issue, maybe the results which you will get will differ.
